version: '3.1'

networks:
  java_10_network:
    driver: bridge
services:
  #  zipkin:
  #    image: openzipkin/zipkin:latest
  #    container_name: java_10_zipkin
  #    ports:
  #      - "9411:9411"
  #    networks:
  #      - java_10_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: java_10_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456789
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - java_10_network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27010:27017"
    networks:
      - java_10_network